namespace KodaMate.Models;

/// <summary>
/// Represents an agenda/schedule item.
/// </summary>
public class AgendaItem
{
    /// <summary>
    /// Unique identifier for the agenda item.
    /// </summary>
    public string Id { get; set; } = Guid.NewGuid().ToString();

    /// <summary>
    /// Title of the event or task.
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Optional description or notes.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Scheduled date and time.
    /// </summary>
    public DateTime ScheduledTime { get; set; }

    /// <summary>
    /// Duration in minutes.
    /// </summary>
    public int DurationMinutes { get; set; } = 30;

    /// <summary>
    /// Whether the item is completed.
    /// </summary>
    public bool IsCompleted { get; set; }

    /// <summary>
    /// Category of the agenda item.
    /// </summary>
    public AgendaCategory Category { get; set; } = AgendaCategory.General;

    /// <summary>
    /// Icon based on category.
    /// </summary>
    public string Icon => Category switch
    {
        AgendaCategory.Medication => "💊",
        AgendaCategory.Exercise => "🏃",
        AgendaCategory.Meal => "🍽️",
        AgendaCategory.Appointment => "📅",
        AgendaCategory.Social => "👥",
        _ => "📌"
    };

    /// <summary>
    /// Formatted time string.
    /// </summary>
    public string TimeString => ScheduledTime.ToString("HH:mm");
}

/// <summary>
/// Represents a smart note generated by Koda.
/// </summary>
public class SmartNote
{
    /// <summary>
    /// Unique identifier for the note.
    /// </summary>
    public string Id { get; set; } = Guid.NewGuid().ToString();

    /// <summary>
    /// Note content.
    /// </summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Whether the note/task is completed.
    /// </summary>
    public bool IsCompleted { get; set; }

    /// <summary>
    /// When the note was created.
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.Now;

    /// <summary>
    /// Source of the note (e.g., "From conversation", "Voice command").
    /// </summary>
    public string Source { get; set; } = "Koda AI";
}

/// <summary>
/// Categories for agenda items.
/// </summary>
public enum AgendaCategory
{
    General,
    Medication,
    Exercise,
    Meal,
    Appointment,
    Social
}
