using KodaMate.Models;

namespace KodaMate.Services;

/// <summary>
/// Interface for Firebase Realtime Database communication.
/// Handles all robot status and data synchronization.
/// </summary>
public interface IFirebaseService
{
    /// <summary>
    /// Gets the current robot status from Firebase.
    /// </summary>
    Task<RobotStatus> GetRobotStatusAsync();

    /// <summary>
    /// Updates the robot power state.
    /// </summary>
    Task SetRobotPowerAsync(bool isPoweredOn);

    /// <summary>
    /// Sends a chat message to Koda.
    /// </summary>
    Task<ChatMessage> SendMessageAsync(string message, string? imagePath = null);

    /// <summary>
    /// Gets conversation history.
    /// </summary>
    Task<List<Conversation>> GetConversationsAsync();

    /// <summary>
    /// Gets notifications from Firebase.
    /// </summary>
    Task<List<Notification>> GetNotificationsAsync();

    /// <summary>
    /// Marks a notification as read.
    /// </summary>
    Task MarkNotificationReadAsync(string notificationId);

    /// <summary>
    /// Gets today's agenda items.
    /// </summary>
    Task<List<AgendaItem>> GetAgendaItemsAsync();

    /// <summary>
    /// Gets smart notes generated by Koda.
    /// </summary>
    Task<List<SmartNote>> GetSmartNotesAsync();

    /// <summary>
    /// Saves app settings to Firebase.
    /// </summary>
    Task SaveSettingsAsync(AppSettings settings);

    /// <summary>
    /// Gets app settings from Firebase.
    /// </summary>
    Task<AppSettings> GetSettingsAsync();

    /// <summary>
    /// Event raised when robot status changes.
    /// </summary>
    event EventHandler<RobotStatus>? OnRobotStatusChanged;
}
